### ISSUE TITLE
Going backwards.

### ISSUE THREAD

**Issue by nilsi** [ragunathjawahar/circular-list-adapter#2]
This works great for going down in the list but backwards it's just like a normal list and hits the start. Is there a way to make it work similar the other way around as when scrolling down? Or I have to scroll down far enough when opening the fragment so I'm sure the user wont scroll whole way back to the start? Thanks

**Comment by ragunathjawahar** [comment]
The least expensive way would be to scoll like you said ;)

**Comment by nilsi** [comment]
Thanks, yeah I went with a PageViewer instead, easier to set up in my case.

**Comment by ragunathjawahar** [comment]
Awesome.
